[project]
org-name = "ballerina"
version = "0.0.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
        artifactId = "mock"
        version = "2.0.0-SNAPSHOT"
        path = "/misc/testerina/modules/testerina-core/build/libs/ballerina-test-0.0.0-java.jar"
        groupId = "ballerina"